---

- name: Get vimfiles repo
  git:
    repo={{ vimfiles_repo }}
    dest={{ workspace_dir }}/vimfiles
  tags:
    - vimfiles

- name: Install vimfiles
  command: "{{ vimfiles_install_cmd }}"
  args:
    chdir: "{{ vimfiles_dir }}"
  tags:
    - vimfiles

- name: Install MacVim
  homebrew:
    name=macvim
    install_options={{ macvim_install_options }}
    state=latest
  tags:
    - vimfiles
    - brew
