---
  
- copy: src=dotfiles/zshrc dest=/Users/{{ ansible_user_id }}/.zshrc backup=yes
- copy: src=dotfiles/vimrc.local dest=/Users/{{ ansible_user_id }}/.vimrc.local backup=yes
- copy: src=dotfiles/vimrc.bundles.local dest=/Users/{{ ansible_user_id }}/.vimrc.bundles.local backup=yes
- copy: src=dotfiles/tmux.conf.local dest=/Users/{{ ansible_user_id }}/.tmux.conf.local backup=yes
- copy: src=dotfiles/editorconfig dest=/Users/{{ ansible_user_id }}/.editorconfig backup=yes
- copy: src=dotfiles/gitignore dest=/Users/{{ ansible_user_id }}/.gitignore backup=yes
- copy: src=dotfiles/gitconfig dest=/Users/{{ ansible_user_id }}/.gitconfig backup=yes
- copy: src=dotfiles/rvmrc dest=/Users/{{ ansible_user_id }}/.rvmrc backup=yes
- copy: src=dotfiles/gemrc dest=/Users/{{ ansible_user_id }}/.gemrc backup=yes
- copy: src=dotfiles/irbrc dest=/Users/{{ ansible_user_id }}/.irbrc backup=yes
- copy: src=dotfiles/npmrc dest=/Users/{{ ansible_user_id }}/.npmrc backup=yes
